#!/bin/bash
# build_hello.sh 
# this script does two things:
# 1. run gyp generator command to generate a toy project from C++ source code
#    which just simply prints out the simple "Hello World!!" string
#    the gyp meta-build system can generate projects for most build systems
#    this script choose two build systems, GNU Make and Ninja for demonstration
# 2. build the toy project generated by gyp, and link the executable code files
#    to symbols in root directory of the project
# 
# *. the script also demonstrate how to generate project files for building
#    libraries, both static and shared (dynamic)
#    after the libraries are built, the script copy them into the lib folder
#    under the root directory of the project
#
# Author: Chuan Zhang, Jan. 26. 2016
# These code and scripts are to support my tutorial "A Brief Introduction to 
# Build Systems".
# 

source clean.sh
gyp hello.gyp -f ninja --depth=. --generator-output=build/ninja
cd build/ninja
ninja -C out/Default/
cd ../../
#cp build/ninja/out/Default/lib/libhello-shared.so lib
cp build/ninja/out/Default/obj/libhello-static.a lib
ln -s -f build/ninja/out/Default/hello-gyp hello-gyp-ninja

gyp hello.gyp -f make --depth=. --generator-output=build/makefiles
cd build/makefiles
make
cd ../../
cp build/makefiles/out/Default/lib.target/libhello-shared.so lib
#cp build/makefiles/out/Default/obj.target/libhello-static.a lib
ln -s -f build/makefiles/out/Default/hello-gyp hello-gyp-make


